probot/adapter-aws-lambda-serverless

index.js
Fixes #3 
This adds cache-manager to the plugin and sets the cache to values that don't assume a long running container.
/cc @bdougie
=> Add cache-manager and use Lambda specific settings for caching

README.md
[Here](https://github.com/probot/serverless-lambda/blob/master/index.js#L24) `serverless` is a named export
so it should be used like 
```js
const { serverless } = require('@probot/serverless-lambda')
```
-----
[View rendered README.md](https://github.com/itaditya/serverless-lambda/blob/patch-1/README.md)
=> named export instead of default export

index.js
Error: Propery `event` is deprecated, use `name`
=> Fix deprecated property in Probot

index.js
Fixes #12.
Credits: To @iamogbz who created this fix
=> fix: undefined event name in webhook handler

package-lock.json, package.json
Further updates dependencies after #21 and cuts a 0.4.0 release. We don't have any automation here, so I'll publish it manually.
=> Further update deps, cut 0.4.0

.github/workflows/release.yml, package-lock.json, package.json
also run `npm audit fix` which "fixed 37731 of 38019 vulnerabilities in 1522 scanned packages
=> ci: semantic-release setup

index.js, package-lock.json, package.json
PR adds compatibility with probot v10.
Credits on @soberstadt
resolves #43
=> Make package compatible with probot v10

index.js
`context.done` is from the pre-node4.10 runtime days of lambda, it was deprecated in favor of callback, which is optionally sidelined in favor of an async/promise-based return. If the function receives no callback and returns a promise or is marked as async, you should simply return/throw in order to actuate the callbacks.
[Proof that it's no longer even in the documentation](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html)
[See the note above the typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/index.d.ts#L448)
While they do technically work... I think relying on them is a bad idea.
=> fix: remove undocumented legacy callbacks

README.md, index.js
Prior to this change, errors would occur when trying to access the old helper file. Probot no longer includes this helper file.
This change adds the new package to make it compatible with the latest version of Probot.
Also updates README with more information on setting this up with environment variables.
-----
[View rendered README.md](https://github.com/KinnersleyM/serverless-lambda/blob/kinnersleym/fix-get-private-key/README.md)
=> Use the new probot package @probot/get-private-key

.gitignore, README.md
-----
[View rendered README.md](https://github.com/axel3rd/adapter-aws-lambda-serverless/blob/doc-improvments/README.md)
=> Fix #61 : Smoke test / Probot v11 migration key points / Common errors

lambda-function.js, package-lock.json, package.json, test/index.test.js
=> Headers insensitive

views/probot.js
This PR updates some asset links that were recently changed (maybe by https://github.com/probot/probot.github.io/pull/367).
=> Fix asset URLs

package-lock.json, package.json, test/index.test.js
The pull request has changes that includes updating the Probot dependency from v11 to v12, updating dependencies that includes Jest, Nock, and Prettier, and modifying the tests to reflect the changes that were introduced by upgrading Probot.
Probot v12 has been released. The adapter has to be updated to be compatible with this latest release of the Probot Framework.
Please view #82  for additional background info.
Useful links that were referenced to make the changes included in this PR:
- https://github.com/probot/probot/pull/1559/commits/1e6eb747d5fbd3fa1edf3523e84060a4554332e5
- https://github.com/probot/adapter-azure-functions/commit/57c82d61adcceb03b4f7c4596da7c04367efaf69#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
**Unit Tests**
1.) Checkout this branch …
=> feat: Support Probot v12

lambda-function.js, test/index.test.js
`callbackWaitsForEmptyEventLoop` is only needed for non-async functions (i.e. functions that use callbacks) and therefore can be safely removed from this package.
See https://github.com/probot/adapter-aws-lambda-serverless/issues/78#issuecomment-1062256878 for more details
=> Remove extraneous `callbackWaitsForEmptyEventLoop` line

lambda-function.js, views/probot.js
This PR restores the static landing page functionality (which is useful as a health check) that was lost during the `v1` to `v2` transition.
It also removes a dead link from the landing page.
**Note:** To avoid merge conflicts, I've based these changes on #91. That PR should be merged first.
=> Restore landing page

README.md
The keyword `webhooks` is used in a lot of different places in the `README.md` file.
This makes it hard to determine which variables, function names, paths, etc. are related.
This PR updates `README.md` to remove that ambiguity.
=> Remove `webhooks` keyword ambiguity from `README.md`

views/probot.js
I originally raised a concern about use of `process.cwd()` in #53.
TL;DR:
- It is a relatively common practice to _bundle_ lambda code before deploying it (e.g. using `esbuild` or `webpack`). This optimization reduce the size of the artifact needing upload, and can also speed up the start time of the lambda.
- This approach is actually built-in to AWS's CDK logic for deploying lambda code -- [see this search](https://github.com/search?q=repo%3Aaws%2Faws-cdk%20esbuild&type=code).
- Trying to grab the `package.json` using `process.cwd()` will always cause an import-time error when running code that was bundled.
=> fix: update template to not rely on filesystem location of package.json

.github/workflows/test.yml, package-lock.json, package.json, test/index.test.js
This PR updates Probot to v13 and replaces nock with fetch-mock.
When attempting to use this package with other packages including functionality built around newer webhook events I came across issues with mismatching `@octokit/webhooks-types` (or just `@octokit/wehooks`)
As per https://github.com/octokit/core.js/issues/551 it is recommended to capture outgoing fetch requests using `fetch-mock` over `nock`.
I have dropped out the dependency for `@probot/get-private-key` as this is not directly used within this package anymore.
=> feat: Support Probot v13

.github/workflows/release.yml, .github/workflows/test.yml
This PR adds NodeJS version 22 to the test workflow since Lambda has recently started supporting this version.
See https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/.
It also updates all the GitHub Actions action versions.
=> Add NodeJS version 22 to test workflow

index.d.ts, package-lock.json, package.json
This PR adds types for Lambda function URLs.
Details about Lambda function URLs can be found below:
- https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/
- https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html
No changes should be necessary to the `createLambdaFunction` implementation since the expected arguments and return types are nearly identical.
=> fix(typescript): add types for `createLambdaFunction()`

index.d.ts
This PR fixes the types that were introduced in #132.
Sorry for the noise!
=> fix(typescript): fix types for `createLambdaFunction()`
